# https://docs.camunda.io/docs/apis-tools/spring-zeebe-sdk/getting-started/
# https://docs.camunda.io/docs/apis-tools/spring-zeebe-sdk/configuration/

zeebe.client:
  cloud:
    region: bru-2
    clusterId: 0a45435e-25d3-413f-aeef-bdd202145f78
    clientId: KdJ4P.kD3Z0P3e9USPatgARuFq9.FOfg
    clientSecret: SGWGCj10b6Yvc8wP6VL3og_ZerJqE_bm5tIDI0cK1alG.yFa~bUze8_4Op0fs_kb
