package org.camunda.consulting.worker;

import io.camunda.zeebe.spring.client.annotation.JobWorker;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

@Component
@Slf4j
public class BunqSampleResponseWorker {

    @JobWorker(type ="bunqresponse")
    public String returnSampleResponse(JobWorker worker){

        return "{\n" +
                "   \"Response\":[\n" +
                "      {\n" +
                "         \"Payment\":{\n" +
                "            \"id\":14041818,\n" +
                "            \"created\":\"2023-08-30 07:34:26.995486\",\n" +
                "            \"updated\":\"2023-08-30 07:34:26.995486\",\n" +
                "            \"metadata_uuid\":\"d687f430-02b2-4775-a5fd-7d687374665f\",\n" +
                "            \"monetary_account_id\":233929,\n" +
                "            \"amount\":{\n" +
                "               \"currency\":\"EUR\",\n" +
                "               \"value\":\"1.83\"\n" +
                "            },\n" +
                "            \"description\":\"bunq Payday 2023-08-30 EUR\",\n" +
                "            \"type\":\"PAYDAY\",\n" +
                "            \"merchant_reference\":null,\n" +
                "            \"maturity_date\":\"2023-08-30\",\n" +
                "            \"alias\":{\n" +
                "               \"iban\":\"NL06BUNQ2059155339\",\n" +
                "               \"is_light\":false,\n" +
                "               \"display_name\":\"A. Niknam\",\n" +
                "               \"avatar\":{\n" +
                "                  \"uuid\":\"703aa4ce-6dd7-4806-8ec5-ca49cef98ab3\",\n" +
                "                  \"image\":[\n" +
                "                     {\n" +
                "                        \"attachment_public_uuid\":\"e4e3bf40-6c05-42f4-8430-ee6afe1a3973\",\n" +
                "                        \"height\":560,\n" +
                "                        \"width\":560,\n" +
                "                        \"content_type\":\"image/jpeg\",\n" +
                "                        \"urls\":[\n" +
                "                           {\n" +
                "                              \"type\":\"ORIGINAL\",\n" +
                "                              \"url\":\"https://bunq-triage-model-storage-public.s3.eu-central-1.amazonaws.com/bunq_file/File/content/b06943915d255ab878920b733ffba216bb5fb0b1e4f290c98b7e368cf0de21d3.jpg\"\n" +
                "                           }\n" +
                "                        ]\n" +
                "                     }\n" +
                "                  ],\n" +
                "                  \"anchor_uuid\":null,\n" +
                "                  \"style\":\"NONE\"\n" +
                "               },\n" +
                "               \"label_user\":{\n" +
                "                  \"uuid\":\"6c0a6ac5-c2c1-41ac-8d10-c0ad473fd801\",\n" +
                "                  \"display_name\":\"A. Niknam\",\n" +
                "                  \"country\":\"NL\",\n" +
                "                  \"avatar\":{\n" +
                "                     \"uuid\":\"d67d1fd9-6342-4a44-9bda-7c21fc77bf1b\",\n" +
                "                     \"image\":[\n" +
                "                        {\n" +
                "                           \"attachment_public_uuid\":\"47a8a5f7-09f9-4ec6-a537-beec6a155459\",\n" +
                "                           \"height\":466,\n" +
                "                           \"width\":466,\n" +
                "                           \"content_type\":\"image/jpeg\",\n" +
                "                           \"urls\":[\n" +
                "                              {\n" +
                "                                 \"type\":\"ORIGINAL\",\n" +
                "                                 \"url\":\"https://bunq-triage-model-storage-public.s3.eu-central-1.amazonaws.com/bunq_file/File/content/02ec648c40d5b9c4c3a132b47f049ab17acc455fa64a0a61baf86433ca5aa467.jpg\"\n" +
                "                              }\n" +
                "                           ]\n" +
                "                        }\n" +
                "                     ],\n" +
                "                     \"anchor_uuid\":\"6c0a6ac5-c2c1-41ac-8d10-c0ad473fd801\",\n" +
                "                     \"style\":\"EASY_GREEN\"\n" +
                "                  },\n" +
                "                  \"public_nick_name\":\"Ali\",\n" +
                "                  \"type\":\"PERSON\",\n" +
                "                  \"id\":191874\n" +
                "               },\n" +
                "               \"country\":\"NL\",\n" +
                "               \"id\":233929\n" +
                "            },\n" +
                "            \"counterparty_alias\":{\n" +
                "               \"iban\":\"NL62BUNQ2060986176\",\n" +
                "               \"is_light\":false,\n" +
                "               \"display_name\":\"bunq\",\n" +
                "               \"avatar\":{\n" +
                "                  \"uuid\":\"9debf55b-70b1-4d43-8d51-d6e7bd42fb5b\",\n" +
                "                  \"image\":[\n" +
                "                     {\n" +
                "                        \"attachment_public_uuid\":\"4b7e0d1d-9167-48ac-990a-70e342c87812\",\n" +
                "                        \"height\":126,\n" +
                "                        \"width\":200,\n" +
                "                        \"content_type\":\"image/jpeg\",\n" +
                "                        \"urls\":[\n" +
                "                           {\n" +
                "                              \"type\":\"ORIGINAL\",\n" +
                "                              \"url\":\"https://bunq-triage-model-storage-public.s3.eu-central-1.amazonaws.com/bunq_file/File/content/6979a145b7ea9ecc3459358122cb560608f02d36d4b8cd6b770f50e36aa35512.jpg\"\n" +
                "                           }\n" +
                "                        ]\n" +
                "                     }\n" +
                "                  ],\n" +
                "                  \"anchor_uuid\":null,\n" +
                "                  \"style\":\"NONE\"\n" +
                "               },\n" +
                "               \"label_user\":{\n" +
                "                  \"uuid\":\"efb68e81-53f9-455b-be32-367437ee1302\",\n" +
                "                  \"display_name\":\"bunq\",\n" +
                "                  \"country\":\"NL\",\n" +
                "                  \"avatar\":{\n" +
                "                     \"uuid\":\"0b305c7e-fa1b-4736-8704-65d90d1bdcb4\",\n" +
                "                     \"image\":[\n" +
                "                        {\n" +
                "                           \"attachment_public_uuid\":\"1d011c65-fb79-4f1d-a82b-af64f7b05cbe\",\n" +
                "                           \"height\":1200,\n" +
                "                           \"width\":1200,\n" +
                "                           \"content_type\":\"image/jpeg\",\n" +
                "                           \"urls\":[\n" +
                "                              {\n" +
                "                                 \"type\":\"ORIGINAL\",\n" +
                "                                 \"url\":\"https://bunq-triage-model-storage-public.s3.eu-central-1.amazonaws.com/bunq_file/File/content/8d83b4b4319567bd78f1cd01abe18989ec022e5079c469a09f2ef29b5873ad85.jpg\"\n" +
                "                              }\n" +
                "                           ]\n" +
                "                        }\n" +
                "                     ],\n" +
                "                     \"anchor_uuid\":\"efb68e81-53f9-455b-be32-367437ee1302\",\n" +
                "                     \"style\":\"NONE\"\n" +
                "                  },\n" +
                "                  \"public_nick_name\":\"bunq\",\n" +
                "                  \"type\":\"COMPANY\",\n" +
                "                  \"id\":7\n" +
                "               },\n" +
                "               \"country\":\"NL\",\n" +
                "               \"id\":430282\n" +
                "            },\n" +
                "            \"attachment\":[\n" +
                "               \n" +
                "            ],\n" +
                "            \"geolocation\":null,\n" +
                "            \"batch_id\":null,\n" +
                "            \"scheduled_id\":null,\n" +
                "            \"address_billing\":null,\n" +
                "            \"address_shipping\":null,\n" +
                "            \"sub_type\":\"PAYMENT\",\n" +
                "            \"status\":\"SETTLED\",\n" +
                "            \"request_reference_split_the_bill\":[\n" +
                "               \n" +
                "            ],\n" +
                "            \"balance_after_mutation\":{\n" +
                "               \"currency\":\"EUR\",\n" +
                "               \"value\":\"16097.96\"\n" +
                "            },\n" +
                "            \"all_auto_save_entry\":[\n" +
                "               \n" +
                "            ],\n" +
                "            \"payment_auto_allocate_instance\":null,\n" +
                "            \"eba_transaction_id\":null\n" +
                "         }\n" +
                "      },\n" +
                "      {\n" +
                "         \"Payment\":{\n" +
                "            \"id\":14039280,\n" +
                "            \"created\":\"2023-08-29 15:54:58.971970\",\n" +
                "            \"updated\":\"2023-08-29 15:54:58.971970\",\n" +
                "            \"metadata_uuid\":\"04635b95-d50f-4990-92d6-033b0cd52ee7\",\n" +
                "            \"monetary_account_id\":446934,\n" +
                "            \"amount\":{\n" +
                "               \"currency\":\"EUR\",\n" +
                "               \"value\":\"1.00\"\n" +
                "            },\n" +
                "            \"description\":\"\",\n" +
                "            \"type\":\"SAVINGS\",\n" +
                "            \"merchant_reference\":null,\n" +
                "            \"maturity_date\":\"2023-08-29\",\n" +
                "            \"alias\":{\n" +
                "               \"iban\":\"NL31BUNQ2061148239\",\n" +
                "               \"is_light\":false,\n" +
                "               \"display_name\":\"TransIP B.V.\",\n" +
                "               \"avatar\":{\n" +
                "                  \"uuid\":\"2bc3f469-f856-4b3b-88c1-7bfc4129c9ac\",\n" +
                "                  \"image\":[\n" +
                "                     {\n" +
                "                        \"attachment_public_uuid\":\"bd40574d-863f-49f7-9a3e-9c8e61a2cc4d\",\n" +
                "                        \"height\":1024,\n" +
                "                        \"width\":1024,\n" +
                "                        \"content_type\":\"image/jpeg\",\n" +
                "                        \"urls\":[\n" +
                "                           {\n" +
                "                              \"type\":\"ORIGINAL\",\n" +
                "                              \"url\":\"https://bunq-triage-model-storage-public.s3.eu-central-1.amazonaws.com/bunq_file/File/content/54ed3d9f3e9eaef067ecd4f54233443fcf58b10a1730b538039fa90a1b1c0c6b.jpg\"\n" +
                "                           }\n" +
                "                        ]\n" +
                "                     }\n" +
                "                  ],\n" +
                "                  \"anchor_uuid\":null,\n" +
                "                  \"style\":\"NONE\"\n" +
                "               },\n" +
                "               \"label_user\":{\n" +
                "                  \"uuid\":\"067f1056-3709-4da9-bcbd-011ff1ab8dd0\",\n" +
                "                  \"display_name\":\"TransIP B.V.\",\n" +
                "                  \"country\":\"NL\",\n" +
                "                  \"avatar\":{\n" +
                "                     \"uuid\":\"3026b537-6b3d-48f4-bc25-333d87626c33\",\n" +
                "                     \"image\":[\n" +
                "                        {\n" +
                "                           \"attachment_public_uuid\":\"136233a7-4516-4e6e-bd6d-078635da788f\",\n" +
                "                           \"height\":640,\n" +
                "                           \"width\":640,\n" +
                "                           \"content_type\":\"image/png\",\n" +
                "                           \"urls\":[\n" +
                "                              {\n" +
                "                                 \"type\":\"ORIGINAL\",\n" +
                "                                 \"url\":\"https://bunq-triage-model-storage-public.s3.eu-central-1.amazonaws.com/bunq_file/File/content/d80402247423e3dd9779b5defc28c3f8be8cf34b464811959224cbeae89e4356.png\"\n" +
                "                              }\n" +
                "                           ]\n" +
                "                        }\n" +
                "                     ],\n" +
                "                     \"anchor_uuid\":\"067f1056-3709-4da9-bcbd-011ff1ab8dd0\",\n" +
                "                     \"style\":\"EASY_GREEN\"\n" +
                "                  },\n" +
                "                  \"public_nick_name\":\"TransIP B.V.\",\n" +
                "                  \"type\":\"COMPANY\",\n" +
                "                  \"id\":191880\n" +
                "               },\n" +
                "               \"country\":\"NL\",\n" +
                "               \"id\":446934\n" +
                "            },\n" +
                "            \"counterparty_alias\":{\n" +
                "               \"iban\":\"NL55BUNQ2059150868\",\n" +
                "               \"is_light\":false,\n" +
                "               \"display_name\":\"TransIP B.V.\",\n" +
                "               \"avatar\":{\n" +
                "                  \"uuid\":\"b2470513-38e6-46d1-b207-12da48367de1\",\n" +
                "                  \"image\":[\n" +
                "                     {\n" +
                "                        \"attachment_public_uuid\":\"147a43ac-8479-4e79-baab-4cc994541d04\",\n" +
                "                        \"height\":1023,\n" +
                "                        \"width\":1024,\n" +
                "                        \"content_type\":\"image/png\",\n" +
                "                        \"urls\":[\n" +
                "                           {\n" +
                "                              \"type\":\"ORIGINAL\",\n" +
                "                              \"url\":\"https://bunq-triage-model-storage-public.s3.eu-central-1.amazonaws.com/bunq_file/File/content/921ece497cd00f4e0cef3f0f63a962c31cf3f8e35311d127d5a7b23be3d074d5.png\"\n" +
                "                           }\n" +
                "                        ]\n" +
                "                     }\n" +
                "                  ],\n" +
                "                  \"anchor_uuid\":null,\n" +
                "                  \"style\":\"NONE\"\n" +
                "               },\n" +
                "               \"label_user\":{\n" +
                "                  \"uuid\":\"067f1056-3709-4da9-bcbd-011ff1ab8dd0\",\n" +
                "                  \"display_name\":\"TransIP B.V.\",\n" +
                "                  \"country\":\"NL\",\n" +
                "                  \"avatar\":{\n" +
                "                     \"uuid\":\"3026b537-6b3d-48f4-bc25-333d87626c33\",\n" +
                "                     \"image\":[\n" +
                "                        {\n" +
                "                           \"attachment_public_uuid\":\"136233a7-4516-4e6e-bd6d-078635da788f\",\n" +
                "                           \"height\":640,\n" +
                "                           \"width\":640,\n" +
                "                           \"content_type\":\"image/png\",\n" +
                "                           \"urls\":[\n" +
                "                              {\n" +
                "                                 \"type\":\"ORIGINAL\",\n" +
                "                                 \"url\":\"https://bunq-triage-model-storage-public.s3.eu-central-1.amazonaws.com/bunq_file/File/content/d80402247423e3dd9779b5defc28c3f8be8cf34b464811959224cbeae89e4356.png\"\n" +
                "                              }\n" +
                "                           ]\n" +
                "                        }\n" +
                "                     ],\n" +
                "                     \"anchor_uuid\":\"067f1056-3709-4da9-bcbd-011ff1ab8dd0\",\n" +
                "                     \"style\":\"EASY_GREEN\"\n" +
                "                  },\n" +
                "                  \"public_nick_name\":\"TransIP B.V.\",\n" +
                "                  \"type\":\"COMPANY\",\n" +
                "                  \"id\":191880\n" +
                "               },\n" +
                "               \"country\":\"NL\",\n" +
                "               \"id\":233934\n" +
                "            },\n" +
                "            \"attachment\":[\n" +
                "               \n" +
                "            ],\n" +
                "            \"geolocation\":null,\n" +
                "            \"batch_id\":null,\n" +
                "            \"scheduled_id\":null,\n" +
                "            \"address_billing\":null,\n" +
                "            \"address_shipping\":null,\n" +
                "            \"sub_type\":\"PAYMENT\",\n" +
                "            \"status\":\"SETTLED\",\n" +
                "            \"request_reference_split_the_bill\":[\n" +
                "               \n" +
                "            ],\n" +
                "            \"balance_after_mutation\":{\n" +
                "               \"currency\":\"EUR\",\n" +
                "               \"value\":\"2.61\"\n" +
                "            },\n" +
                "            \"all_auto_save_entry\":[\n" +
                "               \n" +
                "            ],\n" +
                "            \"payment_auto_allocate_instance\":null,\n" +
                "            \"eba_transaction_id\":null\n" +
                "         }\n" +
                "      }\n" +
                "   ],\n" +
                "   \"Pagination\":{\n" +
                "      \"future_url\":\"/v1/user/191874/admin-payment?count=200&newer_id=14041818\",\n" +
                "      \"newer_url\":null,\n" +
                "      \"older_url\":\"/v1/user/191874/admin-payment?count=200&older_id=13218666\"\n" +
                "   }\n" +
                "} ";
    }
}
